import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './redux/providers'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import NextTopLoader from 'nextjs-toploader';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <NextTopLoader 
      color='#34B233'  />
      <ToastContainer />
      {children}
      </Providers>
      </body>
    </html>
  )
}
